# Copyright 2018 VMware, Inc.
# SPDX-License-Identifier: BSD-2-Clause OR GPL-3.0-only
---
- hosts: 127.0.0.1
  connection: local
  become: yes
  vars_files:
    - answerfile.yml
  tasks:
    - name: Register compute manager
      nsxt_fabric_compute_managers:
          hostname: "{{hostname}}"
          username: "{{username}}"
          password: "{{password}}"
          validate_certs: False
          #compute_manager_id: "25d314b6-97f2-48e2-87b5-f9ce04caf5f8"
          display_name: "{{item.display_name}}"
          server: "{{item.server}}"
          origin_type: "{{item.origin_type}}"
          credential:
            credential_type: "{{item.credential_type}}"
            username: "{{item.username}}"
            password: "{{item.password}}"
            thumbprint: "{{item.thumbprint}}"
          state: present
      with_items:
        - "{{compute_managers}}"
