# Copyright 2018 VMware, Inc.
# SPDX-License-Identifier: BSD-2-Clause OR GPL-3.0-only
---
- hosts: 127.0.0.1
  connection: local
  become: yes
  vars_files:
    - answerfile.yml
  tasks:
    - name: Deploy and register a cluster node VM
      nsxt_controller_manager_auto_deployment:
          hostname: "{{hostname}}"
          username: "{{username}}"
          password: "{{password}}"
          validate_certs: False
          deployment_requests:
          - roles:
            - CONTROLLER
            - MANAGER
            form_factor: "SMALL"
            user_settings:
              cli_password: "Admin!23Admin"
              root_password: "Admin!23Admin"
            deployment_config:
              placement_type: VsphereClusterNodeVMDeploymentConfig
              vc_name: "VC1"
              management_network_id: "network-16"
              hostname: "manager5.vmware.com"
              compute_id: "domain-c8"
              storage_id: "datastore-13"
          #node_id: 7503e86e-c502-46fc-8d91-45a06d314d88
          state: present
