# Copyright 2018 VMware, Inc.
# SPDX-License-Identifier: BSD-2-Clause OR GPL-3.0-only
---
- hosts: 127.0.0.1
  connection: local
  become: yes
  vars_files:
    - answerfile.yml
  tasks:
    - name: Create compute collection transport template
      nsxt_compute_collection_transport_templates:
        hostname: "{{hostname}}"
        username: "{{username}}"
        password: "{{password}}"
        validate_certs: False
        display_name: CCTT1
        compute_collections:
        - compute_manager_name: VC1
          cluster_name: "cl1"
        host_switch_spec:
            resource_type: StandardHostSwitchSpec
            host_switches:
            - host_switch_profiles:
              - name: uplinkProfile1
                type: UplinkHostSwitchProfile
              host_switch_name: hostswitch2
              pnics:
              - device_name: vmnic1
                uplink_name: "uplink-1"
              ip_assignment_spec:
                resource_type: StaticIpPoolSpec
                ip_pool_name: "IPPool-IPV4-1"
        transport_zone_endpoints:
        - transport_zone_name: "TZ2"
        state: present
