# Copyright 2018 VMware, Inc.
# SPDX-License-Identifier: BSD-2-Clause OR GPL-3.0-only
---
- hosts: 127.0.0.1
  connection: local
  become: yes
  vars_files:
    - answerfile.yml
  tasks:
    - name: Add Edge VM
      nsxt_fabric_nodes:
        hostname: "{{hostname}}"
        username: "{{username}}"
        password: "{{password}}"
        validate_certs: False
        resource_type: "EdgeNode"
        display_name: "EdegeNode1"
        #node_id: "58c42d2c-d9bb-4d88-9d9c-3d032ad455e2"
        ip_addresses:
        deployment_config:
          form_factor: "SMALL"
          node_user_settings:
            cli_password: "Admin!23Admin"
            root_password: "Admin!23Admin"
          vm_deployment_config:
            placement_type: VsphereDeploymentConfig
            vc_name: "VC1"
            data_network_ids:
            - network-16
            - network-16
            - network-16
            management_network_id: "network-16"
            hostname: "EdgeVM1"
            compute_id: "domain-c8"
            storage_id: "datastore-13"
            default_gateway_addresses:
            - 10.112.203.253
            management_port_subnets:
            - ip_addresses:
              - 10.112.201.26
              prefix_length: "19"
        state: present
